// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 Giancarlo Erra
// skymap.js
//
// Optional photo sky-mapping fed by ./skymap.json (generated by the site
// build from cited positional data joined with the gallery; schema in
// README.md). Three entry types:
//   comet    followable orrery bodies propagated from JPL SBDB osculating
//            elements fixed at their stated epoch (unperturbed two-body
//            motion, kepler.js), with orbit line, body-list entry and photo
//            strip through photos.json. Each also carries a billboarded
//            thumbnail marker, the same treatment as the deep-sky ones,
//            floated each frame at a small presentational offset beside the
//            comet's current position; it shows only while BOTH the Comets
//            and Sky photos toggles are on.
//   deepsky  billboarded thumbnail markers on a celestial sphere far outside
//            the outermost planetary orbit, along each entry's real ICRS
//            direction rotated into the app's J2000 ecliptic frame; the
//            marker distance is symbolic.
//   earth    pin markers on Earth's globe at each entry's latitude and
//            longitude, attached to Earth's tilt group so the WGCCRE
//            orientation carries them over the real geography; shown only
//            while the camera is near Earth.
// Deep-sky markers and Earth pins share the "Sky photos" control-bar toggle
// (default on) and open the entry's gallery link when clicked; hovering
// shows the gallery title. The comets registered here join the same
// control-bar "Comets" toggle as the well-known comets from data/comets.json
// (the toggle and its consequences live in ui.js and main.js); element
// parsing and scene registration are shared with comets.js so both files
// take the identical propagation path.
//
// Like photos.json, the file is optional: HTTP 404 disables the feature with
// one console line. A file that exists but is malformed is a visible error,
// never ignored. Every position comes from skymap.json; the constants below
// are presentational marker sizing and visibility tuning, not astronomy
// data, and are marked so.

import * as THREE from 'three';
import { parseCometElements, addCometBody } from './comets.js';
import { raDecToUnit, equatorialToEcliptic } from './rotation.js';

const DEG = Math.PI / 180;

// Presentational constants (marker sizing and visibility tuning, not data).
const SKY_RADIUS_FACTOR = 4; // celestial sphere radius, multiples of the overview distance
const SKY_MARKER_PX = 34; // deep-sky marker width on screen, pixels
const COMET_MARKER_OFFSET_PX = 34; // comet photo marker centre offset from the comet dot, pixels
const PIN_PX = 9; // Earth pin diameter on screen, pixels
const PIN_LIFT = 1.005; // pin offset from the centre, body radii (just above the surface)
const EARTH_PIN_VISIBLE_RADII = 60; // show pins when the camera is this close, display radii
const CLICK_MAX_PX = 5; // pointer travel above this is a drag, not a click
const CLICK_MAX_MS = 500; // presses longer than this are not clicks
const PIN_COLOUR = 0xe0a458; // Earth pin tint, accent family, presentational

// ---- validation ----

const TYPES = new Set(['comet', 'deepsky', 'earth']);

function reqString(entry, key, slug) {
  const v = entry[key];
  if (typeof v !== 'string' || v === '') {
    throw new Error(`skymap.json entry ${slug} needs a non-empty "${key}" string`);
  }
  return v;
}

function reqNumber(entry, key, slug) {
  const v = entry[key];
  if (typeof v !== 'number' || !Number.isFinite(v)) {
    throw new Error(`skymap.json entry ${slug} needs a finite "${key}" number`);
  }
  return v;
}

// Shape check for skymap.json (schema in README.md): a top-level "objects"
// object keyed by gallery slug, each entry typed comet, deepsky or earth
// with title, thumb, link and its positional data. Anything off throws; the
// caller surfaces the error visibly. Returns records grouped by type.
export function validateSkymap(data) {
  if (
    typeof data !== 'object' || data === null || Array.isArray(data) ||
    typeof data.objects !== 'object' || data.objects === null || Array.isArray(data.objects)
  ) {
    throw new Error('skymap.json must be an object with an "objects" object keyed by gallery slug');
  }
  const comets = [];
  const deepsky = [];
  const earth = [];
  for (const [slug, entry] of Object.entries(data.objects)) {
    if (typeof entry !== 'object' || entry === null || Array.isArray(entry)) {
      throw new Error(`skymap.json entry ${slug} must be an object`);
    }
    if (!TYPES.has(entry.type)) {
      throw new Error(`skymap.json entry ${slug} has unknown type "${entry.type}"`);
    }
    const common = {
      slug,
      title: reqString(entry, 'title', slug),
      thumb: reqString(entry, 'thumb', slug),
      link: reqString(entry, 'link', slug),
    };
    if (entry.type === 'comet') {
      comets.push({
        ...common,
        name: reqString(entry, 'designation', slug),
        body: reqString(entry, 'body', slug),
        el: parseCometElements(entry, slug, 'skymap.json'),
      });
    } else if (entry.type === 'deepsky') {
      deepsky.push({
        ...common,
        raDeg: reqNumber(entry, 'ra_deg', slug),
        decDeg: reqNumber(entry, 'dec_deg', slug),
      });
    } else {
      earth.push({
        ...common,
        latDeg: reqNumber(entry, 'lat_deg', slug),
        lonDeg: reqNumber(entry, 'lon_deg', slug),
      });
    }
  }
  return { comets, deepsky, earth };
}

// skymap.json is optional site configuration (see README.md): absent file
// (HTTP 404) means the sky-mapping feature is off, stated once on the
// console. Any other failure, including a file that exists but does not
// parse or validate, throws and is surfaced visibly by the caller.
export async function loadSkymap() {
  let res = await fetch('./skymap.json', { cache: 'no-cache' });
  if (res.status === 404) {
    // One retry after a beat: a deploy swapping the directory can 404 an
    // in-flight request for a moment. A genuinely absent file 404s twice.
    await new Promise((resolve) => setTimeout(resolve, 1200));
    res = await fetch('./skymap.json', { cache: 'no-cache' });
  }
  if (res.status === 404) {
    console.info(
      'skymap.json not present: photo sky-mapping disabled (optional site configuration)'
    );
    return null;
  }
  if (!res.ok) {
    throw new Error(`Failed to load ./skymap.json: HTTP ${res.status}`);
  }
  return validateSkymap(await res.json());
}

// ---- feature wiring ----

// data is the validateSkymap result, or null when skymap.json is absent
// (every hook is then inert). Registers comets with the scene, builds the
// deep-sky markers and Earth pins, adds the "Sky photos" toggle to the
// control bar and the marker caveat note to the About panel's technical
// section. skyPhotosOn and cometsOn are the boot states from main.js
// (persisted preference or the defaults); onSkyPhotosToggle reports every
// Sky photos change back, and main.js reports every Comets change through
// setCometsOn. The Comets toggle itself lives in the static markup (ui.js),
// shared with the well-known comets from data/comets.json.
export function initSkymap({
  data,
  sceneApi,
  modes,
  rotationModel,
  skyPhotosOn,
  cometsOn,
  onSkyPhotosToggle,
}) {
  if (data === null) {
    return {
      enabled: false,
      comets: [],
      photoKey() { return null; },
      applyMode() {},
      updateFrame() {},
      setCometsOn() {},
      setLayerVisible() {},
      markers: [],
      pins: [],
      cometMarkers: [],
      markersGroup: null,
      pinsGroup: null,
      cometMarkersGroup: null,
    };
  }

  const { scene, camera, renderer, bodies, maxAu } = sceneApi;
  const labelLayer = document.getElementById('labels');
  const obliquityDeg = rotationModel.obliquityDeg;

  // Ecliptic -> scene axis convention, as documented in modes.js:
  // (x, y, z)_ecliptic maps to (x, z, -y)_scene.
  function eclipticToSceneV(v) {
    return new THREE.Vector3(v.x, v.z, -v.y);
  }

  // Celestial sphere radius: presentational, tied to the overview distance
  // so the markers sit far outside the outermost planetary orbit in both
  // scale modes.
  function skyRadius() {
    return modes.overviewDistance(maxAu) * SKY_RADIUS_FACTOR;
  }

  // ---- comets as orrery bodies ----

  const cometNames = [];
  const photoKeys = new Map();
  for (const comet of data.comets) {
    addCometBody(sceneApi, comet.name, comet.el);
    // el rides along so main.js can read the orbital period for the info
    // card, the same way the comets.json records carry theirs.
    cometNames.push({ name: comet.name, el: comet.el });
    photoKeys.set(comet.name, comet.body);
  }

  // ---- markers and pins ----

  function makeAnchor(entry) {
    const anchor = document.createElement('a');
    anchor.className = 'sky-label';
    anchor.href = entry.link;
    anchor.textContent = entry.title;
    labelLayer.appendChild(anchor);
    return anchor;
  }

  const textureLoader = new THREE.TextureLoader();

  // Deep-sky markers: one camera-facing plane (sprite) per entry, textured
  // with the gallery thumbnail, on the celestial sphere along the entry's
  // ICRS direction. Textures are created lazily, on the first time the
  // markers are shown; a marker stays hidden until its texture has loaded
  // and a failed load throws, never a silent blank.
  const markersGroup = new THREE.Group();
  scene.add(markersGroup);
  const markers = [];
  let markersBuilt = false;

  function buildMarkers() {
    if (markersBuilt) return;
    markersBuilt = true;
    const r = skyRadius();
    for (const entry of data.deepsky) {
      const dir = eclipticToSceneV(
        equatorialToEcliptic(raDecToUnit(entry.raDeg, entry.decDeg), obliquityDeg)
      );
      // Depth-tested so planets, orbit lines and comets in front of the
      // marker's sky position correctly cover it; the pictures belong to
      // the background.
      const material = new THREE.SpriteMaterial({ transparent: true, depthTest: true, depthWrite: false });
      const sprite = new THREE.Sprite(material);
      sprite.renderOrder = -1;
      sprite.visible = false;
      sprite.position.copy(dir).multiplyScalar(r);
      textureLoader.load(
        entry.thumb,
        (texture) => {
          texture.colorSpace = THREE.SRGBColorSpace;
          material.map = texture;
          material.needsUpdate = true;
        },
        undefined,
        () => {
          throw new Error(`Sky marker thumbnail ${entry.thumb} failed to load`);
        }
      );
      markersGroup.add(sprite);
      const marker = { kind: 'deepsky', sprite, dir, anchor: makeAnchor(entry), entry };
      sprite.userData.marker = marker;
      markers.push(marker);
    }
  }

  // Comet photo markers: the same billboarded thumbnail treatment as the
  // deep-sky markers, one per photographed comet, repositioned each frame at
  // a small presentational offset beside the comet's current position (along
  // the camera's right axis, so the thumbnail sits next to the dot at any
  // viewing angle). The group shows only while BOTH the Comets and Sky
  // photos toggles are on; hover and click behave exactly like the deep-sky
  // markers and Earth pins. Textures are created lazily the first time the
  // markers are shown; a marker stays hidden until its texture has loaded
  // and a failed load throws, never a silent blank.
  const cometMarkersGroup = new THREE.Group();
  cometMarkersGroup.visible = false;
  scene.add(cometMarkersGroup);
  const cometMarkers = [];
  let cometMarkersBuilt = false;
  let cometsOnState = cometsOn;

  function buildCometMarkers() {
    if (cometMarkersBuilt) return;
    cometMarkersBuilt = true;
    for (const entry of data.comets) {
      // Depth-tested so planets, orbit lines and comets in front of the
      // marker's sky position correctly cover it; the pictures belong to
      // the background.
      const material = new THREE.SpriteMaterial({ transparent: true, depthTest: true, depthWrite: false });
      const sprite = new THREE.Sprite(material);
      sprite.renderOrder = -1;
      sprite.visible = false;
      textureLoader.load(
        entry.thumb,
        (texture) => {
          texture.colorSpace = THREE.SRGBColorSpace;
          material.map = texture;
          material.needsUpdate = true;
        },
        undefined,
        () => {
          throw new Error(`Comet photo thumbnail ${entry.thumb} failed to load`);
        }
      );
      cometMarkersGroup.add(sprite);
      const marker = {
        kind: 'cometphoto',
        sprite,
        bodyRec: bodies.get(entry.name),
        anchor: makeAnchor(entry),
        entry,
      };
      sprite.userData.marker = marker;
      cometMarkers.push(marker);
    }
  }

  function applyCometMarkerVisibility() {
    const show = markersOn && layerOn && cometsOnState && data.comets.length > 0;
    if (show) buildCometMarkers();
    cometMarkersGroup.visible = show;
    if (!show && hovered && hovered.kind === 'cometphoto') hideHover();
  }

  // Earth pins: dot sprites attached to Earth's tilt group so the WGCCRE
  // orientation and the per-mode radius carry them; positioned on the unit
  // sphere in the mesh-local frame scene.js documents (local +x the prime
  // meridian on the equator, +y the north pole, east longitude towards
  // local -z). Depth testing stays on so the globe occludes far-side pins.
  function latLonToLocal(latDeg, lonDeg) {
    const lat = latDeg * DEG;
    const lon = lonDeg * DEG;
    return new THREE.Vector3(
      Math.cos(lat) * Math.cos(lon),
      Math.sin(lat),
      -Math.cos(lat) * Math.sin(lon)
    );
  }

  function makePinTexture() {
    const size = 64;
    const c = document.createElement('canvas');
    c.width = size;
    c.height = size;
    const ctx = c.getContext('2d');
    ctx.fillStyle = '#ffffff';
    ctx.beginPath();
    ctx.arc(size / 2, size / 2, size / 2 - 2, 0, Math.PI * 2);
    ctx.fill();
    const tex = new THREE.CanvasTexture(c);
    tex.colorSpace = THREE.SRGBColorSpace;
    return tex;
  }

  const earthRec = bodies.get('Earth') || null;
  if (data.earth.length && !earthRec) {
    throw new Error('skymap.json carries earth entries but the scene has no Earth');
  }
  const pinsGroup = new THREE.Group();
  pinsGroup.visible = false;
  const pins = [];
  if (earthRec && data.earth.length) {
    earthRec.tiltGroup.add(pinsGroup);
    const pinTexture = makePinTexture();
    for (const entry of data.earth) {
      const sprite = new THREE.Sprite(
        new THREE.SpriteMaterial({
          map: pinTexture,
          color: PIN_COLOUR,
          transparent: true,
          depthTest: true,
        })
      );
      sprite.position.copy(latLonToLocal(entry.latDeg, entry.lonDeg)).multiplyScalar(PIN_LIFT);
      pinsGroup.add(sprite);
      const pin = { kind: 'earth', sprite, anchor: makeAnchor(entry), entry };
      sprite.userData.marker = pin;
      pins.push(pin);
    }
  }

  // ---- control-bar toggles ----

  // The galactic context view (main.js) swaps the whole sky-photo layer away
  // without touching the Sky photos toggle: layerOn is that gate, ANDed with
  // the toggle everywhere it decides visibility, so leaving the view
  // restores the toggle state unchanged.
  let layerOn = true;

  let markersOn = skyPhotosOn;
  const toggle = document.createElement('button');
  toggle.type = 'button';
  toggle.id = 'sky-photos-toggle';
  toggle.textContent = 'Sky photos';
  toggle.title = 'Show photographed sky objects and locations';
  toggle.setAttribute('aria-pressed', String(markersOn));
  toggle.addEventListener('click', () => {
    markersOn = !markersOn;
    toggle.setAttribute('aria-pressed', String(markersOn));
    applyMarkerVisibility();
    onSkyPhotosToggle(markersOn);
  });
  const infoToggle = document.getElementById('info-toggle');
  infoToggle.parentNode.insertBefore(toggle, infoToggle);

  function applyMarkerVisibility() {
    const show = markersOn && layerOn;
    if (show) buildMarkers();
    markersGroup.visible = show;
    if (!show) {
      pinsGroup.visible = false;
      hideHover();
    }
    applyCometMarkerVisibility();
  }

  // The Comets toggle state, reported by main.js (which owns the toggle's
  // cross-module consequences); the comet photo markers need both toggles.
  function setCometsOn(on) {
    cometsOnState = on;
    applyCometMarkerVisibility();
  }

  // The galactic view gate (see layerOn above).
  function setLayerVisible(on) {
    layerOn = on;
    applyMarkerVisibility();
  }

  // ---- About panel notes (appended to the technical fine print) ----

  // The comet propagation caveat is static in index.html now that comets
  // are core data from comets.json; only the marker note is skymap's own.
  if (data.deepsky.length || data.earth.length) {
    const p = document.createElement('p');
    p.textContent =
      'Sky photo markers point along their objects’ real ICRS positions rotated into the ecliptic frame; their distance from the Sun is symbolic, not a measurement. Earth markers sit at each photograph’s recorded latitude and longitude.';
    document.getElementById('tech-notes').appendChild(p);
  }

  // ---- pointer interaction: hover label and click-through to the gallery ----

  const raycaster = new THREE.Raycaster();
  const pointerNdc = new THREE.Vector2();
  const tmpV = new THREE.Vector3();
  const tmpRight = new THREE.Vector3();
  const canvas = renderer.domElement;
  let hovered = null;
  let pressX = 0;
  let pressY = 0;
  let pressAt = 0;

  function pickMarker(event) {
    pointerNdc.set(
      (event.clientX / window.innerWidth) * 2 - 1,
      -(event.clientY / window.innerHeight) * 2 + 1
    );
    raycaster.setFromCamera(pointerNdc, camera);
    const targets = [];
    if (markersGroup.visible) {
      for (const m of markers) if (m.sprite.visible) targets.push(m.sprite);
    }
    if (cometMarkersGroup.visible) {
      for (const m of cometMarkers) if (m.sprite.visible) targets.push(m.sprite);
    }
    if (pinsGroup.visible) {
      for (const p of pins) targets.push(p.sprite);
    }
    const hits = raycaster.intersectObjects(targets, false);
    return hits.length ? hits[0].object.userData.marker : null;
  }

  function hideHover() {
    if (hovered) {
      hovered.anchor.style.visibility = 'hidden';
      hovered = null;
      canvas.style.cursor = '';
    }
  }

  function updateHoverLabel() {
    if (!hovered) return;
    if (
      (hovered.kind === 'deepsky' && !markersGroup.visible) ||
      (hovered.kind === 'cometphoto' && !cometMarkersGroup.visible) ||
      (hovered.kind === 'earth' && !pinsGroup.visible)
    ) {
      hideHover();
      return;
    }
    hovered.sprite.getWorldPosition(tmpV).applyMatrix4(camera.matrixWorldInverse);
    if (tmpV.z >= 0) {
      hovered.anchor.style.visibility = 'hidden';
      return;
    }
    hovered.sprite.getWorldPosition(tmpV).project(camera);
    const x = (tmpV.x * 0.5 + 0.5) * window.innerWidth;
    const y = (-tmpV.y * 0.5 + 0.5) * window.innerHeight;
    hovered.anchor.style.visibility = 'visible';
    hovered.anchor.style.transform = `translate(${x}px, ${y}px) translate(-50%, -160%)`;
  }

  canvas.addEventListener('pointermove', (event) => {
    const marker = markersOn && layerOn ? pickMarker(event) : null;
    if (marker !== hovered) {
      hideHover();
      hovered = marker;
      canvas.style.cursor = marker ? 'pointer' : '';
    }
  });
  canvas.addEventListener('pointerdown', (event) => {
    pressX = event.clientX;
    pressY = event.clientY;
    pressAt = performance.now();
  });
  canvas.addEventListener('pointerup', (event) => {
    if (!markersOn || !layerOn) return;
    if (performance.now() - pressAt > CLICK_MAX_MS) return;
    if (Math.hypot(event.clientX - pressX, event.clientY - pressY) > CLICK_MAX_PX) return;
    const marker = pickMarker(event);
    if (marker) marker.anchor.click();
  });

  // ---- per-frame and per-mode updates ----

  // A mode change moves the celestial sphere with the overview distance so
  // the markers stay far outside the outermost orbit at either scale.
  function applyMode() {
    const r = skyRadius();
    for (const m of markers) {
      m.sprite.position.copy(m.dir).multiplyScalar(r);
    }
  }

  // Runs every frame after the scene update, with the camera settled:
  // scales markers and pins to a constant on-screen size, gates pin
  // visibility on the camera's distance to Earth, and repositions the hover
  // label.
  function updateFrame() {
    const h = window.innerHeight;
    const fovFactor = Math.tan((camera.fov / 2) * DEG);

    if (markersGroup.visible) {
      for (const m of markers) {
        const map = m.sprite.material.map;
        if (!map || !map.image) {
          m.sprite.visible = false;
          continue;
        }
        m.sprite.visible = true;
        const dist = m.sprite.position.distanceTo(camera.position);
        const worldPerPx = (2 * dist * fovFactor) / h;
        const w = SKY_MARKER_PX * worldPerPx;
        m.sprite.scale.set(w, w / (map.image.width / map.image.height), 1);
      }
    }

    if (cometMarkersGroup.visible) {
      // Camera right axis in world space: the marker floats beside the comet
      // on screen whatever the viewing direction.
      tmpRight.setFromMatrixColumn(camera.matrixWorld, 0);
      for (const m of cometMarkers) {
        const map = m.sprite.material.map;
        if (!map || !map.image) {
          m.sprite.visible = false;
          continue;
        }
        m.sprite.visible = true;
        const dist = m.bodyRec.worldPos.distanceTo(camera.position);
        const worldPerPx = (2 * dist * fovFactor) / h;
        m.sprite.position
          .copy(m.bodyRec.worldPos)
          .addScaledVector(tmpRight, COMET_MARKER_OFFSET_PX * worldPerPx);
        const w = SKY_MARKER_PX * worldPerPx;
        m.sprite.scale.set(w, w / (map.image.width / map.image.height), 1);
      }
    }

    if (earthRec && pins.length) {
      const near =
        markersOn && layerOn &&
        camera.position.distanceTo(earthRec.worldPos) <
          EARTH_PIN_VISIBLE_RADII * modes.bodyRadius(earthRec.radiusKm);
      pinsGroup.visible = near;
      if (near) {
        const parentScale = earthRec.tiltGroup.scale.x; // uniform, set by applyMode
        for (const p of pins) {
          p.sprite.getWorldPosition(tmpV);
          const dist = tmpV.distanceTo(camera.position);
          const worldPerPx = (2 * dist * fovFactor) / h;
          p.sprite.scale.setScalar((PIN_PX * worldPerPx) / parentScale);
        }
      }
    }

    updateHoverLabel();
  }

  applyMarkerVisibility();

  return {
    enabled: true,
    comets: cometNames,
    // photos.json key for a comet's display name, joining the photo strip
    // to the comet body; null for every other name.
    photoKey(name) {
      return photoKeys.get(name) || null;
    },
    applyMode,
    updateFrame,
    setCometsOn,
    setLayerVisible,
    // Scene objects exposed for inspection (headless checks and debugging).
    markers,
    pins,
    cometMarkers,
    markersGroup,
    pinsGroup,
    cometMarkersGroup,
  };
}
